version: '3'

services:
  notifications:
    build: ./ras-notifications/notifications
    environment:
      - TZ=Europe/Lisbon
    networks:
      - notifications
    depends_on:
      - notifications-postgres
      - notifications-redis

  notifications-postgres:
    image: postgres
    volumes:
      - notifications-postgres-data:/var/lib/postgresql/data
    networks:
      - notifications
    environment:
      - POSTGRES_DB=notifications
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - TZ=Europe/Lisbon

  notifications-redis:  # Define Redis service
    image: redis
    networks:
      - notifications
    depends_on:
      - notifications-postgres
    environment:
      - TZ=Europe/Lisbon


  users-mysql:
    image: mysql:latest
    volumes:
      - users-mysql-data:/var/lib/mysql
    networks:
      - users
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Europe/Lisbon
    
  users:
    build: ./RAS_USER/users_backend
    environment:
      - TZ=Europe/Lisbon
    networks:
      - users
    depends_on:
      wait-for-db-users:
        condition: service_completed_successfully

  
  wait-for-db-users:
    image: atkrad/wait4x
    networks:
      - users
    depends_on:
      - users-mysql
    command: tcp users-mysql:3306 -t 30s -i 250ms

  rooms:
    build: ./Ras-room-ms/
    environment:
      DB_HOST: rooms_mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: RoomsDB
    depends_on:
      - rooms_mysql
    networks:
      - rooms

  rooms_mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: RoomsDB
    networks:
      - rooms
    volumes:
      - rooms-mysql-data:/var/lib/mysql

  nginx:
    build: ./api-layer
    ports:
      - "80:8000"
    networks:
      - notifications
      - users
      - rooms
    depends_on:
      - notifications
      - users
      - rooms


    

volumes:
  notifications-postgres-data:
  users-mysql-data:
  rooms-mysql-data:

networks:
  notifications:
    driver: bridge
  users:
    driver: bridge
  rooms:
    driver: bridge
